select
    DocEntry                                    as doc_entry,
    DocNum                                      as quote_number,
    CAST(DocDate as date)                       as issue_date,
    CAST(DocDueDate as date)                    as expiration_date,
    CAST(CreateDate as date)                    as creation_date,
    CAST(UpdateDate as date)                    as updated_date,
    UpdateTS                                    as update_ts,
    DocStatus                                   as document_status,
    CANCELED                                    as canceled,
    CardCode                                    as customer_code,
    CardName                                    as customer_name,
    SlpCode                                     as salesperson_code,
    BPLId                                       as branch_id,
    SeqCode                                     as series_code,
    PeyMethod                                   as payment_method,
    CAST(DocTotal as decimal(20, 6))            as document_total,
    CAST(DocTotalSy as decimal(20, 6))          as document_total_system_currency,
    CAST(GrosProfit as decimal(20, 6))          as gross_profit,
    CAST(DiscSum as decimal(20, 6))             as header_discount,
    CAST(VatSum as decimal(20, 6))              as total_taxes,
    U_LOAD_KIT                                  as load_kit,
    U_Store                                      as store_code,
    _ingested_at
from {{ source('raw_sap', 'OQUT') }}
