select
    DocEntry                                                        as doc_entry,
    LineNum                                                         as line_number,
    ItemCode                                                        as item_code,
    Dscription                                                      as item_description,
    CAST(Quantity as decimal(20, 6))                                as quantity,
    CAST(Price as decimal(20, 6))                                   as unit_price,
    CAST(PriceBefDi as decimal(20, 6))                              as price_before_discount,
    CAST(DiscPrcnt as decimal(18, 4))                               as discount_percentage,
    CAST(LineTotal as decimal(20, 6))                               as line_total,
    CAST(VatSum as decimal(20, 6))                                  as total_taxes,
    CAST(INMPrice as decimal(20, 6))                                as inventory_cost_price,
    LineStatus                                                      as line_status,
    Usage                                                           as usage_id,
    CFOPCode                                                        as cfop,
    WhsCode                                                         as warehouse_code,
    BaseEntry                                                       as source_doc_entry,
    CAST(BaseType as int)                                           as source_document_type,
    {{ normalize_brazilian_decimal('U_BDI_PRICE', 18, 2) }}              as bdi_price,
    {{ normalize_brazilian_decimal('U_COST_PRICE', 18, 2) }}            as cost_price,
    {{ normalize_brazilian_decimal('U_MARGIN', 18, 4) }}                 as margin,
    _ingested_at
from {{ source('raw_sap', 'INV1') }}
