USE msdb;
GO
/* =====================================================================
   SQL Agent jobs by FREQUENCY (generated by generate_sql.py).
   The frequency follows the dbt DAGs. Schedules come DISABLED
   (@enabled = 0 on the schedule) -- enable after validating (see docs/04_runbook...).
   ===================================================================== */

-------------------------------------------------------------------------------
-- Job: ingestion_hourly
-------------------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'ingestion_hourly')
    EXEC msdb.dbo.sp_delete_job @job_name = N'ingestion_hourly', @delete_unused_schedule = 1;
GO
EXEC msdb.dbo.sp_add_job @job_name = N'ingestion_hourly', @enabled = 1, @description = N'Hourly SAP ingestion (dims + sales) -- follows common/sales (7-22h).';
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_hourly', @step_name = N'hourly group (dims + light sales)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ingest_group @group = ''hourly'';',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_hourly', @step_name = N'sales invoice family (OINV+INV1+INV6+INV12)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_fam_sales_invoice;',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_hourly', @step_name = N'quote family (OQUT+QUT1+QUT12)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_fam_quote;',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_hourly', @step_name = N'sales order family (ORDR+RDR1)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_fam_sales_order;',
     @on_success_action = 1, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobschedule
     @job_name = N'ingestion_hourly',
     @name = N'sched_ingestion_hourly',
     @enabled = 0,
     @freq_type = 4,
     @freq_interval = 1,
     @freq_subday_type = 8,
     @freq_subday_interval = 1,
     @active_start_time = 063000,
     @active_end_time = 213000;
EXEC msdb.dbo.sp_add_jobserver @job_name = N'ingestion_hourly';
GO
-------------------------------------------------------------------------------
-- Job: ingestion_inventory
-------------------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'ingestion_inventory')
    EXEC msdb.dbo.sp_delete_job @job_name = N'ingestion_inventory', @delete_unused_schedule = 1;
GO
EXEC msdb.dbo.sp_add_job @job_name = N'ingestion_inventory', @enabled = 1, @description = N'SAP inventory ingestion 6x/day -- follows dbt_inventory (7,10,13,16,19,22).';
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_inventory', @step_name = N'OINM (incremental_upsert)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_OINM;',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_inventory', @step_name = N'inventory group (OITW + ITM1 full)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ingest_group @group = ''inventory'';',
     @on_success_action = 1, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobschedule
     @job_name = N'ingestion_inventory',
     @name = N'sched_ingestion_inventory',
     @enabled = 0,
     @freq_type = 4,
     @freq_interval = 1,
     @freq_subday_type = 8,
     @freq_subday_interval = 3,
     @active_start_time = 063000,
     @active_end_time = 213000;
EXEC msdb.dbo.sp_add_jobserver @job_name = N'ingestion_inventory';
GO
-------------------------------------------------------------------------------
-- Job: ingestion_daily_movement
-------------------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'ingestion_daily_movement')
    EXEC msdb.dbo.sp_delete_job @job_name = N'ingestion_daily_movement', @delete_unused_schedule = 1;
GO
EXEC msdb.dbo.sp_add_job @job_name = N'ingestion_daily_movement', @enabled = 1, @description = N'SAP OINM ingestion before the daily close -- follows dbt_daily_movement (5h).';
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_daily_movement', @step_name = N'OINM (incremental_upsert)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_OINM;',
     @on_success_action = 1, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobschedule
     @job_name = N'ingestion_daily_movement',
     @name = N'sched_ingestion_daily_movement',
     @enabled = 0,
     @freq_type = 4,
     @freq_interval = 1,
     @active_start_time = 040000;
EXEC msdb.dbo.sp_add_jobserver @job_name = N'ingestion_daily_movement';
GO
-------------------------------------------------------------------------------
-- Job: ingestion_purchases
-------------------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'ingestion_purchases')
    EXEC msdb.dbo.sp_delete_job @job_name = N'ingestion_purchases', @delete_unused_schedule = 1;
GO
EXEC msdb.dbo.sp_add_job @job_name = N'ingestion_purchases', @enabled = 1, @description = N'Daily SAP purchases ingestion -- follows dbt_purchases_finance (6h).';
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_purchases', @step_name = N'purchases group (full)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ingest_group @group = ''purchases'';',
     @on_success_action = 1, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobschedule
     @job_name = N'ingestion_purchases',
     @name = N'sched_ingestion_purchases',
     @enabled = 0,
     @freq_type = 4,
     @freq_interval = 1,
     @active_start_time = 050000;
EXEC msdb.dbo.sp_add_jobserver @job_name = N'ingestion_purchases';
GO
-------------------------------------------------------------------------------
-- Job: ingestion_nightly
-------------------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'ingestion_nightly')
    EXEC msdb.dbo.sp_delete_job @job_name = N'ingestion_nightly', @delete_unused_schedule = 1;
GO
EXEC msdb.dbo.sp_add_job @job_name = N'ingestion_nightly', @enabled = 1, @description = N'Nightly SAP ingestion (no scheduled dbt consumer): ledger, payments, orphans.';
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_nightly', @step_name = N'JDT1 (incremental_append)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_JDT1;',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_nightly', @step_name = N'OJDT (incremental_append)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ing_OJDT;',
     @on_success_action = 3, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobstep
     @job_name = N'ingestion_nightly', @step_name = N'nightly group (full)',
     @subsystem = N'TSQL', @database_name = N'SAP_MIRROR', @command = N'EXEC etl.usp_ingest_group @group = ''nightly'';',
     @on_success_action = 1, @on_fail_action = 2, @retry_attempts = 1, @retry_interval = 2;
EXEC msdb.dbo.sp_add_jobschedule
     @job_name = N'ingestion_nightly',
     @name = N'sched_ingestion_nightly',
     @enabled = 0,
     @freq_type = 4,
     @freq_interval = 1,
     @active_start_time = 030000;
EXEC msdb.dbo.sp_add_jobserver @job_name = N'ingestion_nightly';
GO