select
    DocEntry                            as doc_entry,
    DocNum                              as invoice_number,
    CAST(DocDate as date)               as issue_date,
    CAST(DocDueDate as date)            as due_date,
    CAST(TaxDate as date)               as accrual_date,
    CAST(UpdateDate as date)            as updated_date,
    UpdateTS                            as update_ts,
    DocStatus                           as document_status,
    CANCELED                            as canceled,
    CardCode                            as supplier_code,
    CardName                            as supplier_name,
    BPLId                               as branch_id,
    BPLName                             as branch_name,
    SeqCode                             as series_code,
    Serial                              as series_number,
    PeyMethod                           as payment_method,
    TransId                             as ledger_transaction_id,
    CAST(DocTotal as decimal(20, 6))    as document_total,
    CAST(VatSum as decimal(20, 6))      as total_taxes,
    CAST(GrosProfit as decimal(20, 6))  as gross_profit,
    Comments                            as notes,
    U_Store                              as store_code,
    _ingested_at
from {{ source('raw_sap', 'OPCH') }}
