select
    ItemCode                                as item_code,
    ItemName                                as item_name,
    CAST(UpdateDate as date)                as updated_date,
    UpdateTS                                as update_ts,
    FirmCode                                as manufacturer_code,
    InvntryUom                              as unit_of_measure,
    InvntItem                               as inventory_item,
    SellItem                                as sales_item,
    PrchseItem                              as purchase_item,
    CAST(OnHand as decimal(20, 6))          as inventory_quantity,
    ItmsGrpCod                              as item_group_code,
    frozenFor                               as inactive,
    validFor                                as active,
    U_CLASS                                as class,
    U_FAMILY                               as family,
    U_SUB_CLASS                            as sub_class,
    U_CURVE                                 as abc_curve,
    U_MADE_TO_ORDER                             as made_to_order,
    U_LEAD_TIME                             as lead_time_days,
    U_SCORE                             as score,
    CAST(SWeight1 as decimal(20, 6))        as gross_weight,
    _ingested_at
from {{ source('raw_sap', 'OITM') }}
