select
    DocEntry                          as doc_entry,
    DocNum                            as payment_number,
    DocType                           as payment_type,
    CAST(DocDate as date)             as payment_date,
    CAST(TaxDate as date)             as accrual_date,
    CAST(DocDueDate as date)          as due_date,
    CAST(UpdateDate as date)          as updated_date,
    UpdateTS                          as update_ts,
    Canceled                          as canceled,
    CardCode                          as partner_code,
    CardName                          as partner_name,
    BPLId                             as branch_id,
    CAST(DocTotal as decimal(20, 6))  as payment_total,
    DocCurr                           as currency,
    CAST(CashSum as decimal(20, 6))   as cash_amount,
    CAST(TrsfrSum as decimal(20, 6))  as transfer_amount,
    CAST(CheckSum as decimal(20, 6))  as check_amount,
    CAST(CreditSum as decimal(20, 6)) as credit_amount,
    CAST(NoDocSum as decimal(20, 6))  as amount_without_document,
    TransId                           as ledger_transaction_id,
    JrnlMemo                          as historical,
    _ingested_at
from {{ source('raw_sap', 'OVPM') }}
