USE SAP_MIRROR;
GO
/* =====================================================================
   etl.usp_ing_fam_quote  (generated by _generator/generate_sql.py -- do NOT edit by hand)
   Incremental via OPENQUERY(HANA_LINK). Watermark read from raw_sap itself.
   Frame: applock + audit.ingestion_log + BEGIN TRAN/CATCH (no TRUNCATE).
   ===================================================================== */
CREATE OR ALTER PROCEDURE etl.usp_ing_fam_quote
    @execution_id UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @execution_id IS NULL SET @execution_id = NEWID();

    DECLARE @row_count INT = 0, @log_id INT = NULL, @msg NVARCHAR(4000),
            @wm_date NVARCHAR(10), @wm_ts INT, @wm_de BIGINT, @cond NVARCHAR(MAX),
            @filtro NVARCHAR(MAX), @rs NVARCHAR(MAX), @q NVARCHAR(MAX);
    DECLARE @lock_res NVARCHAR(255) = N'etl.ingestion.fam_quote', @lock INT;

    EXEC @lock = sp_getapplock @Resource = @lock_res, @LockMode = 'Exclusive',
                               @LockOwner = 'Session', @LockTimeout = 5000;
    IF @lock < 0 THROW 50002, N'Ingestion already in progress for fam_quote.', 1;

    BEGIN TRY
        -- pre-capture the COMBINED watermark of header OQUT (BEFORE reloading) -- sort_order is critical
        -- (UpdateDate, UpdateTS) catch RE-EDITED docs; MAX(DocEntry) catches NEW docs.
        -- DocEntry is SAP's monotonic PK: a new document is born with a higher DocEntry. An
        -- old re-edited doc has a high UpdateTS but a low DocEntry, so it does NOT raise the
        -- DocEntry ceiling -- this avoids poisoning the cutoff and hiding the new invoices
        -- that have a lower UpdateTS.
        SELECT TOP 1 @wm_date = CONVERT(varchar(10), [UpdateDate], 23), @wm_ts = ISNULL([UpdateTS], 0)
        FROM raw_sap.[OQUT] WHERE [UpdateDate] IS NOT NULL
        ORDER BY [UpdateDate] DESC, [UpdateTS] DESC;
        SELECT @wm_de = MAX([DocEntry]) FROM raw_sap.[OQUT];
        SET @cond = CASE WHEN @wm_date IS NOT NULL
            THEN N'"UpdateDate" > ''' + @wm_date + N''' OR ("UpdateDate" = ''' + @wm_date + N''' AND "UpdateTS" > ' + CAST(@wm_ts AS NVARCHAR(20)) + N') OR "DocEntry" > ' + CAST(ISNULL(@wm_de, 0) AS NVARCHAR(20))
            ELSE NULL END;
        -- HEADER OQUT (incremental_upsert)
        SET @filtro = CASE WHEN @wm_date IS NOT NULL THEN N' WHERE ' + @cond ELSE N'' END;
        -- self-heal: close a previous stuck run of this table_name (the applock guarantees it is dead)
        UPDATE audit.ingestion_log SET status = N'interrupted', finished_at = SYSDATETIME(),
               error_message = N'interrupted: previous run did not finish (closed when starting a new load)'
        WHERE table_name = N'OQUT' AND status = N'running';
        INSERT INTO audit.ingestion_log (execution_id, table_name, strategy, frequency, started_at, status)
        VALUES (@execution_id, N'OQUT', N'incremental_upsert', N'daily', SYSDATETIME(), N'running');
        SET @log_id = SCOPE_IDENTITY();
        SET @row_count = 0;
        SET @rs = N'SELECT "DocEntry", "DocNum", "DocDate", "DocDueDate", "DocStatus", "DocTotal", "DocTotalSy", "GrosProfit", "CANCELED", "CardCode", "CardName", "SlpCode", "PeyMethod", "DiscSum", "U_LOAD_KIT", "U_Store", "SeqCode", "BPLId", "CreateDate", "UpdateDate", "UpdateTS", "VatSum", "Max1099" FROM "SAP_PROD"."OQUT"' + @filtro;
        BEGIN TRAN;
            SET @q = N'SELECT * INTO #d FROM OPENQUERY(HANA_LINK, ''' + REPLACE(@rs, '''', '''''') + N''');'
                   + N' DELETE d FROM raw_sap.[OQUT] d INNER JOIN #d s ON d.[DocEntry] = s.[DocEntry];'
                   + N' INSERT INTO raw_sap.[OQUT] ([DocEntry], [DocNum], [DocDate], [DocDueDate], [DocStatus], [DocTotal], [DocTotalSy], [GrosProfit], [CANCELED], [CardCode], [CardName], [SlpCode], [PeyMethod], [DiscSum], [U_LOAD_KIT], [U_Store], [SeqCode], [BPLId], [CreateDate], [UpdateDate], [UpdateTS], [VatSum], [Max1099]) SELECT [DocEntry], [DocNum], [DocDate], [DocDueDate], [DocStatus], [DocTotal], [DocTotalSy], [GrosProfit], [CANCELED], [CardCode], [CardName], [SlpCode], [PeyMethod], [DiscSum], [U_LOAD_KIT], [U_Store], [SeqCode], [BPLId], [CreateDate], [UpdateDate], [UpdateTS], [VatSum], [Max1099] FROM #d;'
                   + N' SET @out = @@ROWCOUNT;';
            EXEC sp_executesql @q, N'@out INT OUTPUT', @out = @row_count OUTPUT;
        COMMIT;
        UPDATE audit.ingestion_log
            SET finished_at = SYSDATETIME(), row_count = @row_count, status = N'success' WHERE id = @log_id;
        -- LINE QUT1 (incremental_via_header, header OQUT)
        SET @filtro = CASE WHEN @wm_date IS NOT NULL
            THEN N' WHERE "DocEntry" IN (SELECT "DocEntry" FROM "SAP_PROD"."OQUT" WHERE ' + @cond + N')'
            ELSE N'' END;
        -- self-heal: close a previous stuck run of this table_name (the applock guarantees it is dead)
        UPDATE audit.ingestion_log SET status = N'interrupted', finished_at = SYSDATETIME(),
               error_message = N'interrupted: previous run did not finish (closed when starting a new load)'
        WHERE table_name = N'QUT1' AND status = N'running';
        INSERT INTO audit.ingestion_log (execution_id, table_name, strategy, frequency, started_at, status)
        VALUES (@execution_id, N'QUT1', N'incremental_via_header', N'daily', SYSDATETIME(), N'running');
        SET @log_id = SCOPE_IDENTITY();
        SET @row_count = 0;
        SET @rs = N'SELECT "DocEntry", "LineNum", "ItemCode", "Dscription", "Quantity", "Price", "PriceBefDi", "LineTotal", "VatSum", "INMPrice", "DiscPrcnt", "LineStatus", "Usage", "CFOPCode", "U_BDI_PRICE", "U_COST_PRICE", "WhsCode", "BaseEntry", "BaseType", "U_MARGIN" FROM "SAP_PROD"."QUT1"' + @filtro;
        BEGIN TRAN;
            SET @q = N'SELECT * INTO #d FROM OPENQUERY(HANA_LINK, ''' + REPLACE(@rs, '''', '''''') + N''');'
                   + N' DELETE d FROM raw_sap.[QUT1] d INNER JOIN (SELECT DISTINCT [DocEntry] FROM #d) s ON d.[DocEntry] = s.[DocEntry];'
                   + N' INSERT INTO raw_sap.[QUT1] ([DocEntry], [LineNum], [ItemCode], [Dscription], [Quantity], [Price], [PriceBefDi], [LineTotal], [VatSum], [INMPrice], [DiscPrcnt], [LineStatus], [Usage], [CFOPCode], [U_BDI_PRICE], [U_COST_PRICE], [WhsCode], [BaseEntry], [BaseType], [U_MARGIN]) SELECT [DocEntry], [LineNum], [ItemCode], [Dscription], [Quantity], [Price], [PriceBefDi], [LineTotal], [VatSum], [INMPrice], [DiscPrcnt], [LineStatus], [Usage], [CFOPCode], [U_BDI_PRICE], [U_COST_PRICE], [WhsCode], [BaseEntry], [BaseType], [U_MARGIN] FROM #d;'
                   + N' SET @out = @@ROWCOUNT;';
            EXEC sp_executesql @q, N'@out INT OUTPUT', @out = @row_count OUTPUT;
        COMMIT;
        UPDATE audit.ingestion_log
            SET finished_at = SYSDATETIME(), row_count = @row_count, status = N'success' WHERE id = @log_id;
        -- LINE QUT12 (incremental_via_header, header OQUT)
        SET @filtro = CASE WHEN @wm_date IS NOT NULL
            THEN N' WHERE "DocEntry" IN (SELECT "DocEntry" FROM "SAP_PROD"."OQUT" WHERE ' + @cond + N')'
            ELSE N'' END;
        -- self-heal: close a previous stuck run of this table_name (the applock guarantees it is dead)
        UPDATE audit.ingestion_log SET status = N'interrupted', finished_at = SYSDATETIME(),
               error_message = N'interrupted: previous run did not finish (closed when starting a new load)'
        WHERE table_name = N'QUT12' AND status = N'running';
        INSERT INTO audit.ingestion_log (execution_id, table_name, strategy, frequency, started_at, status)
        VALUES (@execution_id, N'QUT12', N'incremental_via_header', N'daily', SYSDATETIME(), N'running');
        SET @log_id = SCOPE_IDENTITY();
        SET @row_count = 0;
        SET @rs = N'SELECT "DocEntry", "MainUsage" FROM "SAP_PROD"."QUT12"' + @filtro;
        BEGIN TRAN;
            SET @q = N'SELECT * INTO #d FROM OPENQUERY(HANA_LINK, ''' + REPLACE(@rs, '''', '''''') + N''');'
                   + N' DELETE d FROM raw_sap.[QUT12] d INNER JOIN (SELECT DISTINCT [DocEntry] FROM #d) s ON d.[DocEntry] = s.[DocEntry];'
                   + N' INSERT INTO raw_sap.[QUT12] ([DocEntry], [MainUsage]) SELECT [DocEntry], [MainUsage] FROM #d;'
                   + N' SET @out = @@ROWCOUNT;';
            EXEC sp_executesql @q, N'@out INT OUTPUT', @out = @row_count OUTPUT;
        COMMIT;
        UPDATE audit.ingestion_log
            SET finished_at = SYSDATETIME(), row_count = @row_count, status = N'success' WHERE id = @log_id;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @msg = LEFT(ERROR_MESSAGE(), 4000);
        IF @log_id IS NOT NULL
            UPDATE audit.ingestion_log
                SET finished_at = SYSDATETIME(), status = N'error', error_message = @msg
                WHERE id = @log_id;
        EXEC sp_releaseapplock @Resource = @lock_res, @LockOwner = 'Session';
        THROW;
    END CATCH

    EXEC sp_releaseapplock @Resource = @lock_res, @LockOwner = 'Session';
END
GO
