USE SAP_MIRROR;
GO
/* =====================================================================
   etl.usp_ing_OINM  (generated by _generator/generate_sql.py -- do NOT edit by hand)
   Incremental via OPENQUERY(HANA_LINK). Watermark read from raw_sap itself.
   Frame: applock + audit.ingestion_log + BEGIN TRAN/CATCH (no TRUNCATE).
   ===================================================================== */
CREATE OR ALTER PROCEDURE etl.usp_ing_OINM
    @execution_id UNIQUEIDENTIFIER = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @execution_id IS NULL SET @execution_id = NEWID();

    DECLARE @row_count INT = 0, @log_id INT = NULL, @msg NVARCHAR(4000),
            @wm_date NVARCHAR(10), @wm_ts INT, @wm_de BIGINT, @cond NVARCHAR(MAX),
            @filtro NVARCHAR(MAX), @rs NVARCHAR(MAX), @q NVARCHAR(MAX);
    DECLARE @lock_res NVARCHAR(255) = N'etl.ingestion.OINM', @lock INT;

    EXEC @lock = sp_getapplock @Resource = @lock_res, @LockMode = 'Exclusive',
                               @LockOwner = 'Session', @LockTimeout = 5000;
    IF @lock < 0 THROW 50002, N'Ingestion already in progress for OINM.', 1;

    BEGIN TRY
        SELECT @wm_date = CONVERT(varchar(10), MAX([DocDate]), 23) FROM raw_sap.[OINM];
        SET @filtro = N' WHERE "DocDate" >= ''2025-07-01'''
                    + CASE WHEN @wm_date IS NOT NULL THEN N' AND "DocDate" >= ''' + @wm_date + N'''' ELSE N'' END;
        -- self-heal: close a previous stuck run of this table_name (the applock guarantees it is dead)
        UPDATE audit.ingestion_log SET status = N'interrupted', finished_at = SYSDATETIME(),
               error_message = N'interrupted: previous run did not finish (closed when starting a new load)'
        WHERE table_name = N'OINM' AND status = N'running';
        INSERT INTO audit.ingestion_log (execution_id, table_name, strategy, frequency, started_at, status)
        VALUES (@execution_id, N'OINM', N'incremental_upsert', N'diaria', SYSDATETIME(), N'running');
        SET @log_id = SCOPE_IDENTITY();
        SET @row_count = 0;
        SET @rs = N'SELECT "TransNum", "DocDate", "ItemCode", "Warehouse", "InQty", "OutQty", "TransValue", "CalcPrice", "Balance", "TransType", "CreatedBy", "BASE_REF", "DocLineNum" FROM "SAP_PROD"."OINM"' + @filtro;
        BEGIN TRAN;
            SET @q = N'SELECT * INTO #d FROM OPENQUERY(HANA_LINK, ''' + REPLACE(@rs, '''', '''''') + N''');'
                   + N' DELETE d FROM raw_sap.[OINM] d INNER JOIN #d s ON d.[TransNum] = s.[TransNum];'
                   + N' INSERT INTO raw_sap.[OINM] ([TransNum], [DocDate], [ItemCode], [Warehouse], [InQty], [OutQty], [TransValue], [CalcPrice], [Balance], [TransType], [CreatedBy], [BASE_REF], [DocLineNum]) SELECT [TransNum], [DocDate], [ItemCode], [Warehouse], [InQty], [OutQty], [TransValue], [CalcPrice], [Balance], [TransType], [CreatedBy], [BASE_REF], [DocLineNum] FROM #d;'
                   + N' SET @out = @@ROWCOUNT;';
            EXEC sp_executesql @q, N'@out INT OUTPUT', @out = @row_count OUTPUT;
        COMMIT;
        UPDATE audit.ingestion_log
            SET finished_at = SYSDATETIME(), row_count = @row_count, status = N'success' WHERE id = @log_id;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        SET @msg = LEFT(ERROR_MESSAGE(), 4000);
        IF @log_id IS NOT NULL
            UPDATE audit.ingestion_log
                SET finished_at = SYSDATETIME(), status = N'error', error_message = @msg
                WHERE id = @log_id;
        EXEC sp_releaseapplock @Resource = @lock_res, @LockOwner = 'Session';
        THROW;
    END CATCH

    EXEC sp_releaseapplock @Resource = @lock_res, @LockOwner = 'Session';
END
GO
